[tool.poetry]
name = "posetta"
version = "0.0.5"
description = "The Universal Translator of Geodetic Coordinate File Formats"
authors = ["Nordic Geodetic Commision <geir.arne.hjelle@kartverket.no>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/NordicGeodesy/posetta"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering",
    ]
keywords = ["geodesy", "coordinate", "position", "format", "converter"]

[tool.poetry.dependencies]
python = ">=3.6"
pandas = ">=0.23.0"
fastkml = ">=0.11.0"
lxml = ">=4.2"
click = ">=7.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
posetta = "posetta.__main__:cli"
posetta_gui = "posetta.__main__:gui"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
