[tool.poetry]
name = "BotSpot"
version = "0.1.2"
description = ""
authors = ["Rohit Ram <rohit.ram@anu.edu.au>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
